services:
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BASE_API_URL=https://jsonplaceholder.typicode.com
      - BASE_UI_URL=https://the-internet.herokuapp.com
      - HEADLESS=true
      - BROWSER=chromium
      - LOG_LEVEL=INFO
      - REPORT_DIR=/app/reports
    volumes:
      - ./reports:/app/reports
      - ./logs:/app/logs
      - ./screenshots:/app/screenshots
